# Generated by Django 4.0.5 on 2022-12-11 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255, unique=True)),
                ('currency', models.CharField(blank=True, choices=[('USD', 'Usd'), ('SOUM', 'Soum')], default='SOUMS', max_length=255, null=True)),
                ('main_language', models.CharField(blank=True, max_length=255, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='')),
                ('phone', models.CharField(max_length=255)),
                ('wifi_password', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField()),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('theme', models.TextField(blank=True, choices=[('orange', 'January'), ('FEBRUARY', 'February'), ('MARCH', 'March'), ('DECEMBER', 'December')], default='orange', null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
